apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: json2delta
  namespace: default
spec:
  type: Python
  mode: cluster
  image: timzsu1104/spark:4.0.0-cloud-1
  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///opt/app/json2delta.py

  sparkConf:
    spark.sql.catalogImplementation: hive
    spark.sql.sources.commitProtocolClass: org.apache.spark.internal.io.cloud.PathOutputCommitProtocol
    spark.sql.parquet.output.committer.class: org.apache.spark.internal.io.cloud.BindingParquetOutputCommitter

    spark.sql.warehouse.dir: "s3a://hive/warehouse/tablespace/managed/hive"

    # DeltaLake
    spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog

  hadoopConf:
    hive.metastore.uris: thrift://hive-metastore:9083

    fs.s3a.endpoint: http://minio.default.svc.cluster.local:9000
    fs.s3a.access.key: hive
    fs.s3a.secret.key: hivehive
    fs.s3a.path.style.access: "true"
    fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

    fs.s3a.connection.timeout: "60000"
    fs.s3a.connection.acquisition.timeout: "60000"
    fs.s3a.connection.establish.timeout: "30000"
    fs.s3a.connection.idle.time: "60000"
    fs.s3a.connection.request.timeout: "60000"
    fs.s3a.connection.ttl: "300000"
    fs.s3a.threads.keepalivetime: "60"

    fs.s3a.committer.name: magic
    fs.s3a.bucket.all.committer.magic.enabled: "true"

    fs.s3a.multipart.purge: "false"
    fs.s3a.multipart.purge.age: "86400"

    mapreduce.fileoutputcommitter.algorithm.version: "2"
    mapreduce.fileoutputcommitter.cleanup-failures.ignored: "true"
    mapreduce.fileoutputcommitter.marksuccessfuljobs: "false"

  sparkVersion: 4.0.0

  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark

    volumeMounts:
      - name: app-code
        mountPath: /opt/app

  executor:
    cores: 1
    instances: 1
    memory: 512m

  volumes:
    - name: app-code
      configMap:
        name: python-cmap