tags:
  bundle: true

wait: true

service:
  type: NodePort
  nodePort: 31001

computeComponent:
  extraVolumes:
    - name: minio-ca
      secret:
        secretName: minio-ca
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /opt/minio-ca
      readOnly: true
  extraEnvVars:
    - name: AWS_CA_BUNDLE
      value: /opt/minio-ca/ca.crt
    - name: SSL_CERT_FILE
      value: /opt/minio-ca/ca.crt

metaComponent:
  extraVolumes:
    - name: minio-ca
      secret:
        secretName: minio-ca
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /opt/minio-ca
      readOnly: true
  extraEnvVars:
    - name: AWS_CA_BUNDLE
      value: /opt/minio-ca/ca.crt
    - name: SSL_CERT_FILE
      value: /opt/minio-ca/ca.crt

compactorComponent:
  extraVolumes:
    - name: minio-ca
      secret:
        secretName: minio-ca
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /opt/minio-ca
      readOnly: true
  extraEnvVars:
    - name: AWS_CA_BUNDLE
      value: /opt/minio-ca/ca.crt
    - name: SSL_CERT_FILE
      value: /opt/minio-ca/ca.crt

frontendComponent:
  extraVolumes:
    - name: minio-ca
      secret:
        secretName: minio-ca
  extraVolumeMounts:
    - name: minio-ca
      mountPath: /opt/minio-ca
      readOnly: true
  extraEnvVars:
    - name: AWS_CA_BUNDLE
      value: /opt/minio-ca/ca.crt
    - name: SSL_CERT_FILE
      value: /opt/minio-ca/ca.crt
