# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hms-metastore-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: "/mnt/data/hms-metastore"
